In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier

In [3]:
# read training data
data = pd.read_csv('panic_disorder_dataset_training.csv')
data.head()
train_data_set = pd.DataFrame(data)
train_data_set.head()

Participant ID  Age  Gender Family History Personal History  \
0               1   38    Male             No              Yes   
1               2   51    Male             No               No   
2               3   32  Female            Yes               No   
3               4   64  Female             No               No   
4               5   31    Male            Yes               No   

  Current Stressors             Symptoms  Severity Impact on Life  \
0          Moderate  Shortness of breath      Mild           Mild   
1              High        Panic attacks      Mild           Mild   
2              High        Panic attacks      Mild    Significant   
3          Moderate           Chest pain  Moderate       Moderate   
4          Moderate        Panic attacks      Mild       Moderate   

  Demographics Medical History  Psychiatric History Substance Use  \
0        Rural        Diabetes     Bipolar disorder           NaN   
1        Urban          Asthma     Anxiety disorder         Drugs   
2        Urban        Diabetes  Depressive disorder           NaN   
3        Rural        Diabetes                  NaN           NaN   
4        Rural          Asthma                  NaN         Drugs   

  Coping Mechanisms Social Support Lifestyle Factors  Panic Disorder Diagnosis  
0       Socializing           High     Sleep quality                         0  
1          Exercise           High     Sleep quality                         0  
2   Seeking therapy       Moderate          Exercise                         0  
3        Meditation           High          Exercise                         0  
4   Seeking therapy            Low     Sleep quality                         0

In [4]:
# read test data
data = pd.read_csv('panic_disorder_dataset_testing.csv')
test_data_set = pd.DataFrame(data)
test_data_set.head()

Participant ID  Age  Gender Family History Personal History  \
0               1   41    Male            Yes               No   
1               2   20  Female            Yes               No   
2               3   32    Male            Yes              Yes   
3               4   41  Female            Yes              Yes   
4               5   36  Female            Yes               No   

  Current Stressors             Symptoms  Severity Impact on Life  \
0              High  Shortness of breath      Mild           Mild   
1               Low  Shortness of breath      Mild    Significant   
2              High        Panic attacks    Severe           Mild   
3          Moderate  Shortness of breath  Moderate    Significant   
4              High           Chest pain    Severe    Significant   

  Demographics Medical History  Psychiatric History Substance Use  \
0        Urban        Diabetes     Bipolar disorder       Alcohol   
1        Urban          Asthma     Anxiety disorder         Drugs   
2        Rural   Heart disease     Bipolar disorder         Drugs   
3        Urban   Heart disease     Anxiety disorder           NaN   
4        Rural          Asthma  Depressive disorder           NaN   

  Coping Mechanisms Social Support Lifestyle Factors  Panic Disorder Diagnosis  
0   Seeking therapy            Low          Exercise                         0  
1          Exercise           High              Diet                         0  
2        Meditation       Moderate          Exercise                         0  
3          Exercise           High     Sleep quality                         0  
4   Seeking therapy            Low          Exercise                         0

In [5]:
#strore of the data except xAttack of training dataset
train_x=train_data_set.drop('Panic Disorder Diagnosis',axis=1)
#store xAttack columns data of training dataset
train_y=train_data_set['Panic Disorder Diagnosis']
#type casting to integer
train_y =train_y.astype('int')
#strore of the data except xAttack of test dataset
test_x=test_data_set.drop('Panic Disorder Diagnosis',axis=1)
#store xAttack columns data of testing dataset
test_y=test_data_set['Panic Disorder Diagnosis']
#type casting to integer
test_y =test_y.astype('int')

In [6]:
label_encoder = LabelEncoder()
# Iterate over each column in the dataset
for column in train_x.columns:
    # Check if the column contains string values
    if train_x[column].dtype == "object":
        # Fit label encoder on the column
        label_encoder.fit(train_x[column])
        # Transform the string values to integers
        train_x[column] = label_encoder.transform(train_x[column])
for column in test_x.columns:
    # Check if the column contains string values
    if test_x[column].dtype == "object":
        # Fit label encoder on the column
        label_encoder.fit(test_x[column])
        # Transform the string values to integers
        test_x[column] = label_encoder.transform(test_x[column])

In [7]:
#preprocessing using StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
#scaling of training dataset
X_train_scaled = scaler.fit_transform(train_x)
X_test_scaled = scaler.fit_transform(test_x)

In [8]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import metrics
abc = AdaBoostClassifier(n_estimators=100, learning_rate=0.1)
ada_model = abc.fit(X_train_scaled, train_y)
y_pred = ada_model.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(test_y, y_pred))


Accuracy: 0.96205


In [9]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score

# Confusion matrix
cm=confusion_matrix(test_y, y_pred.round())
print(cm)

[[19096    63]
 [  696   145]]


In [10]:
#random forest classifier using SKlearn module
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=0)
#fittness of the model on training dataset
rf.fit(train_x, train_y)
print("Accuracy on training set: {:.3f}".format(rf.score(train_x, train_y)))
print("Accuracy on test set: {:.3f}".format(rf.score(test_x, test_y)))

Accuracy on training set: 1.000
Accuracy on test set: 0.999


In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
dt = DecisionTreeClassifier()
sv = SVC(kernel ='poly', degree=2)

In [12]:
# Apply Decision Tree on dataset and good the best Scores
dt.fit(X_train_scaled, train_y)
print("Accuracy on training set: {:.3f}".format(dt.score(X_train_scaled, train_y)))
print("Accuracy on test set: {:.3f}".format(dt.score(X_test_scaled, test_y)))
y_pred = dt.predict(X_test_scaled)
cm=confusion_matrix(test_y, y_pred.round())
print(cm)

Accuracy on training set: 1.000
Accuracy on test set: 0.999
[[19152     7]
 [    5   836]]


In [13]:
# Apply support vector machine
sv.fit(X_train_scaled, train_y)
print("Accuracy on training set: {:.3f}".format(sv.score(X_train_scaled, train_y)))
print("Accuracy on test set: {:.3f}".format(sv.score(X_test_scaled, test_y)))

y_pred = sv.predict(X_test_scaled)
cm=confusion_matrix(test_y, y_pred.round())
print(cm)

Accuracy on training set: 0.957
Accuracy on test set: 0.958
[[19159     0]
 [  841     0]]


In [14]:
# Apply KNN for Pridctionon dataset
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train_scaled, train_y)
print("Accuracy on training set: {:.3f}".format(knn.score(X_train_scaled, train_y)))
print("Accuracy on test set: {:.3f}".format(knn.score(X_test_scaled, test_y)))

AttributeError: 'NoneType' object has no attribute 'split'

In [18]:
# Apply Naive Bays on same dataset
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_scaled, train_y)
print("Accuracy on training set: {:.3f}".format(gnb.score(X_train_scaled, train_y)))
print("Accuracy on test set: {:.3f}".format(gnb.score(X_test_scaled, test_y)))

Accuracy on training set: 0.712
Accuracy on test set: 0.958


In [20]:
# Apply feed forward Deep neural network 
mlp = MLPClassifier(solver='sgd', hidden_layer_sizes=(45,30,15),activation='relu', random_state=1, learning_rate_init=0.2, alpha =0.09,
                    learning_rate='invscaling',momentum=0.9, max_iter=100,early_stopping=True, validation_fraction=0.1,verbose=True, 
                   )
#MLP model fittness on traning dataset
mlp.fit(X_train_scaled, train_y)
#accuracy on training dataset
pred_mlp = mlp.predict(X_test_scaled)

print(classification_report(test_y , pred_mlp))

print("Accuracy on training set: {:.3f}".format(mlp.score(X_train_scaled, train_y)))
#accuracy on test dataset
print("Accuracy on test set: {:.3f}".format(mlp.score(X_test_scaled, test_y)))


Iteration 1, loss = 0.09060320
Validation score: 0.983500
Iteration 2, loss = 0.06883074
Validation score: 0.979700
Iteration 3, loss = 0.06112896
Validation score: 0.981700
Iteration 4, loss = 0.05788768
Validation score: 0.982200
Iteration 5, loss = 0.05594042
Validation score: 0.982800
Iteration 6, loss = 0.05458608
Validation score: 0.983200
Iteration 7, loss = 0.05360643
Validation score: 0.983700
Iteration 8, loss = 0.05286987
Validation score: 0.983700
Iteration 9, loss = 0.05228854
Validation score: 0.984200
Iteration 10, loss = 0.05181731
Validation score: 0.984300
Iteration 11, loss = 0.05143275
Validation score: 0.984400
Iteration 12, loss = 0.05110663
Validation score: 0.984200
Iteration 13, loss = 0.05082660
Validation score: 0.984100
Iteration 14, loss = 0.05058200
Validation score: 0.984200
Iteration 15, loss = 0.05036625
Validation score: 0.984300
Iteration 16, loss = 0.05017670
Validation score: 0.984300
Iteration 17, loss = 0.04999862
Validation score: 0.984400
Iterat